services:
  - type: web
    name: luxbid-frontend
    env: node
    nodeVersion: 20.12.0
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://luxbid-backend.onrender.com"
      - key: PORT
        value: 3000
    healthCheckPath: /
    plan: free
