services:
  - type: web
    name: luxbid-frontend
    env: node
    nodeVersion: 20.12.0
    buildCommand: chmod +x scripts/deploy-render.sh && ./scripts/deploy-render.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://luxbid-backend.onrender.com"
      - key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        value: "G-PXGXDYQDY3"
      - key: PORT
        value: 3000
      - key: BASIC_AUTH_USER
        value: "luxbid"
      - key: BASIC_AUTH_PASSWORD
        value: "luxbid2024"
      - key: NEXT_PUBLIC_BASIC_AUTH_USER
        value: "luxbid"
      - key: NEXT_PUBLIC_BASIC_AUTH_PASSWORD
        value: "luxbid2024"
    healthCheckPath: /
    plan: starter
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
